package br.ucs.classleague.infrastructure.presentation.views;

import br.ucs.classleague.domain.SchoolClass;
import br.ucs.classleague.infrastructure.presentation.controllers.RegisterController;
import br.ucs.classleague.infrastructure.presentation.controllers.TournamentController;
import java.awt.event.ActionEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class GUI extends javax.swing.JFrame {
    
    private RegisterController registerController = new RegisterController(this);
    private TournamentController tournamentController = new TournamentController(this);
    
    public int prevClassNumber = -1;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        studentRegisterDialog = new javax.swing.JDialog();
        classRegisterDialog = new javax.swing.JDialog();
        mainTabbedPane = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        mainTopPanel = new javax.swing.JPanel();
        mainInnerTopPanel = new javax.swing.JPanel();
        jTournamentLabel = new javax.swing.JLabel();
        searchTournamentField = new javax.swing.JTextField();
        searchTournamentBtn = new javax.swing.JButton();
        addTournamentBtn = new javax.swing.JButton();
        jTournamentSelectScrollPane = new javax.swing.JScrollPane();
        jTournamentSelectTable = new javax.swing.JTable();
        mainSeparator = new javax.swing.JSeparator();
        mainBottomPanel = new javax.swing.JPanel();
        mainInnerBottomPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tournamentRegister = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        tournamentRegisterPanel = new javax.swing.JPanel();
        tournamentNameLabel = new javax.swing.JLabel();
        tournamentNameField = new javax.swing.JTextField();
        tournamentStartDateLabel = new javax.swing.JLabel();
        tournamentEndDateLabel = new javax.swing.JLabel();
        tournamentStartDateField = new javax.swing.JFormattedTextField();
        tournamentEndDateField = new javax.swing.JFormattedTextField();
        tournamentSportLabel = new javax.swing.JLabel();
        tournamentSportComboBox = new javax.swing.JComboBox<>(registerController.showSportsNames());
        tournamentRegisterButton = new javax.swing.JButton();
        tournamentScrollPane = new java.awt.ScrollPane();
        tournamentTeamsLabel = new javax.swing.JLabel();
        classRegister = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jClassNameField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jClassNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jClassShift = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jClassCycle = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        studentRegister2 = new javax.swing.JPanel();
        jStudentRegisterTitle = new javax.swing.JLabel();
        jStudentRegisterPanel = new javax.swing.JPanel();
        jRegisterStudentNameLabel = new javax.swing.JLabel();
        jRegisterStudentNameField = new javax.swing.JTextField();
        jRegisterStudentGenderLabel = new javax.swing.JLabel();
        jRegisterStudentGenderField = new javax.swing.JTextField();
        JRegisterStudentClassLabel = new javax.swing.JLabel();
        jRegisterStudentClassComboBox = new javax.swing.JComboBox<>();
        JRegisterStudentFatherNameLabel = new javax.swing.JLabel();
        jRegisterStudentFatherNameField = new javax.swing.JTextField();
        jRegisterStudentMotherNameLabel = new javax.swing.JLabel();
        jRegisterStudentMotherNameField = new javax.swing.JTextField();
        JStudentRegisterButton = new javax.swing.JButton();
        jRegisterStudentBirthdateLabel = new javax.swing.JLabel();
        jRegisterStudentSurnameLabel = new javax.swing.JLabel();
        jRegisterStudentSurnameField = new javax.swing.JTextField();
        jRegisterStudentCPFLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRegisterStudentTelephoneField = new javax.swing.JFormattedTextField();
        jRegisterStudentBirthdateField = new javax.swing.JFormattedTextField();
        jRegisterStudentCPFField = new javax.swing.JFormattedTextField();
        teamRegisterPanel = new javax.swing.JPanel();
        jTeamRegisterTitle = new javax.swing.JLabel();
        jInnerTeamRegisterPanel = new javax.swing.JPanel();
        jTeamRegisterNameLabel = new javax.swing.JLabel();
        jTeamRegisterNameField = new javax.swing.JTextField();
        jTeamRegisterAcronymLabel = new javax.swing.JLabel();
        jTeamRegisterAcronymField = new javax.swing.JTextField();
        jTeamRegisterSportLabel = new javax.swing.JLabel();
        jTeamRegisterSportComboBox = new javax.swing.JComboBox<>(registerController.showSportsNames());
        jTeamRegisterClassPickerLabel = new javax.swing.JLabel();
        jTeamRegisterClassPickerComboBox = new javax.swing.JComboBox<>();
        jTeamRegisterButton = new javax.swing.JButton();
        jTeamRegisterStudentsScrollPane = new javax.swing.JScrollPane();
        jTeamRegisterStudentsTable =  new javax.swing.JTable(registerController.getTeamRegisterTableModel(0));
        coachRegister = new javax.swing.JPanel();
        jCoachRegisterTitle1 = new javax.swing.JLabel();
        coachRegisterPanel = new javax.swing.JPanel();
        coachSurnameLabel = new javax.swing.JLabel();
        coachNameField = new javax.swing.JTextField();
        coachGenderLabel = new javax.swing.JLabel();
        coachGenderField = new javax.swing.JTextField();
        coachNameLabel1 = new javax.swing.JLabel();
        coachSurnameField1 = new javax.swing.JTextField();
        coachPhoneLabel = new javax.swing.JLabel();
        coachCPFLabel = new javax.swing.JLabel();
        coachBirthDateLabel = new javax.swing.JLabel();
        coachSportLabel = new javax.swing.JLabel();
        coachSportField = new javax.swing.JTextField();
        JCoachRegisterButton1 = new javax.swing.JButton();
        coachBirthDateField = new javax.swing.JFormattedTextField();
        coachCPFField = new javax.swing.JFormattedTextField();
        coachPhoneField = new javax.swing.JFormattedTextField();

        studentRegisterDialog.setAlwaysOnTop(true);
        studentRegisterDialog.setMinimumSize(new java.awt.Dimension(500, 500));
        studentRegisterDialog.setModal(true);
        studentRegisterDialog.setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout studentRegisterDialogLayout = new javax.swing.GroupLayout(studentRegisterDialog.getContentPane());
        studentRegisterDialog.getContentPane().setLayout(studentRegisterDialogLayout);
        studentRegisterDialogLayout.setHorizontalGroup(
            studentRegisterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        studentRegisterDialogLayout.setVerticalGroup(
            studentRegisterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        classRegisterDialog.setAlwaysOnTop(true);
        classRegisterDialog.setMinimumSize(new java.awt.Dimension(500, 500));
        classRegisterDialog.setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout classRegisterDialogLayout = new javax.swing.GroupLayout(classRegisterDialog.getContentPane());
        classRegisterDialog.getContentPane().setLayout(classRegisterDialogLayout);
        classRegisterDialogLayout.setHorizontalGroup(
            classRegisterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        classRegisterDialogLayout.setVerticalGroup(
            classRegisterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassLeague");
        setMinimumSize(null);
        setSize(new java.awt.Dimension(0, 0));

        mainTabbedPane.setPreferredSize(new java.awt.Dimension(1024, 768));
        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        mainTopPanel.setLayout(new java.awt.GridBagLayout());

        jTournamentLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTournamentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTournamentLabel.setText("Torneios");

        searchTournamentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTournamentFieldActionPerformed(evt);
            }
        });

        searchTournamentBtn.setText("Pesquisar");

        addTournamentBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addTournamentBtn.setText("+");
        addTournamentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTournamentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainInnerTopPanelLayout = new javax.swing.GroupLayout(mainInnerTopPanel);
        mainInnerTopPanel.setLayout(mainInnerTopPanelLayout);
        mainInnerTopPanelLayout.setHorizontalGroup(
            mainInnerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainInnerTopPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(addTournamentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 626, Short.MAX_VALUE)
                .addComponent(searchTournamentField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTournamentBtn)
                .addGap(31, 31, 31))
            .addComponent(jTournamentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainInnerTopPanelLayout.setVerticalGroup(
            mainInnerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainInnerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTournamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainInnerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTournamentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTournamentBtn)
                    .addComponent(addTournamentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainTopPanel.add(mainInnerTopPanel, gridBagConstraints);

        jTournamentSelectTable.setModel(tournamentController.updateTournamentListCells());
        jTournamentSelectTable.setRowHeight(40);
        jTournamentSelectTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTournamentSelectTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTournamentSelectTable.setShowGrid(false);
        jTournamentSelectTable.setShowHorizontalLines(true);
        jTournamentSelectTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if (!e.getValueIsAdjusting()){
                    System.out.println(jTournamentSelectTable.getSelectedRow());
                }
            }
        });
        jTournamentSelectScrollPane.setViewportView(jTournamentSelectTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 50, 15, 50);
        mainTopPanel.add(jTournamentSelectScrollPane, gridBagConstraints);

        mainPanel.add(mainTopPanel);
        mainPanel.add(mainSeparator);

        mainBottomPanel.setLayout(new javax.swing.BoxLayout(mainBottomPanel, javax.swing.BoxLayout.Y_AXIS));

        mainInnerBottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(null);
        jButton1.setMinimumSize(null);
        jButton1.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainInnerBottomPanel.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setMaximumSize(null);
        jButton2.setMinimumSize(null);
        jButton2.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainInnerBottomPanel.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setMaximumSize(null);
        jButton3.setMinimumSize(null);
        jButton3.setPreferredSize(new java.awt.Dimension(120, 120));
        mainInnerBottomPanel.add(jButton3);

        mainBottomPanel.add(mainInnerBottomPanel);

        mainPanel.add(mainBottomPanel);

        mainTabbedPane.addTab("Início", mainPanel);

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cadastro de Torneios");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tournamentRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));
        tournamentRegisterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        tournamentNameLabel.setText("Nome do torneio");

        tournamentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournamentNameFieldActionPerformed(evt);
            }
        });

        tournamentStartDateLabel.setText("Data de início");

        tournamentEndDateLabel.setText("Data de encerramento");

        try {
            tournamentStartDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tournamentEndDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tournamentSportLabel.setText("Esporte");

        tournamentSportComboBox.setAutoscrolls(true);
        tournamentSportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournamentSportComboBoxActionPerformed(evt);
            }
        });

        tournamentRegisterButton.setText("Cadastrar");
        tournamentRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournamentRegisterButtonActionPerformed(evt);
            }
        });

        tournamentTeamsLabel.setText("Selecione os times participantes:");

        javax.swing.GroupLayout tournamentRegisterPanelLayout = new javax.swing.GroupLayout(tournamentRegisterPanel);
        tournamentRegisterPanel.setLayout(tournamentRegisterPanelLayout);
        tournamentRegisterPanelLayout.setHorizontalGroup(
            tournamentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournamentRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tournamentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tournamentRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tournamentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tournamentNameLabel)
                    .addComponent(tournamentSportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tournamentEndDateLabel)
                    .addComponent(tournamentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tournamentStartDateLabel)
                    .addComponent(tournamentStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tournamentEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tournamentSportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tournamentTeamsLabel)))
            .addGroup(tournamentRegisterPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(tournamentRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tournamentRegisterPanelLayout.setVerticalGroup(
            tournamentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournamentRegisterPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(tournamentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentStartDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tournamentEndDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tournamentSportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tournamentSportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tournamentTeamsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tournamentRegisterLayout = new javax.swing.GroupLayout(tournamentRegister);
        tournamentRegister.setLayout(tournamentRegisterLayout);
        tournamentRegisterLayout.setHorizontalGroup(
            tournamentRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournamentRegisterLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(tournamentRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tournamentRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addGap(328, 328, 328))
        );
        tournamentRegisterLayout.setVerticalGroup(
            tournamentRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tournamentRegisterLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Cadastro de Torneio", tournamentRegister);

        classRegister.setLayout(new java.awt.GridBagLayout());

        title4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Cadastro de Turmas");
        title4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        classRegister.add(title4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel14.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel5.add(jLabel14, gridBagConstraints);

        jClassNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel5.add(jClassNameField, gridBagConstraints);

        jLabel15.setText("Número");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel5.add(jLabel15, gridBagConstraints);

        jClassNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(jClassNumber, gridBagConstraints);

        jLabel16.setText("Turno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel5.add(jLabel16, gridBagConstraints);

        jClassShift.setModel(new javax.swing.DefaultComboBoxModel<>(SchoolClass.SchoolShift.values()));
        jClassShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassShiftActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(jClassShift, gridBagConstraints);

        jLabel17.setText("Ciclo Escolar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel5.add(jLabel17, gridBagConstraints);

        jClassCycle.setModel(new javax.swing.DefaultComboBoxModel<>(SchoolClass.EducationalCycle.values()));
        jClassCycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassCycleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jClassCycle, gridBagConstraints);

        jButton8.setText("Cadastrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerClassAction(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 10, 0);
        jPanel5.add(jButton8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        classRegister.add(jPanel5, gridBagConstraints);

        mainTabbedPane.addTab("Cadastro de Turma", classRegister);

        studentRegister2.setLayout(new java.awt.GridBagLayout());

        jStudentRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jStudentRegisterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStudentRegisterTitle.setText("Cadastro de Alunos");
        jStudentRegisterTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        studentRegister2.add(jStudentRegisterTitle, gridBagConstraints);

        jStudentRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));
        jStudentRegisterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jStudentRegisterPanel.setPreferredSize(new java.awt.Dimension(328, 480));

        jRegisterStudentNameLabel.setText("Nome");

        jRegisterStudentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentNameFieldActionPerformed(evt);
            }
        });

        jRegisterStudentGenderLabel.setText("Sexo");

        jRegisterStudentGenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentGenderFieldActionPerformed(evt);
            }
        });

        JRegisterStudentClassLabel.setText("Turma");

        registerController.showClassesNumbers();
        jRegisterStudentClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentClassComboBoxActionPerformed(evt);
            }
        });

        JRegisterStudentFatherNameLabel.setText("Nome do pai");

        jRegisterStudentFatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentFatherNameFieldActionPerformed(evt);
            }
        });

        jRegisterStudentMotherNameLabel.setText("Nome da mãe");

        jRegisterStudentMotherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentMotherNameFieldActionPerformed(evt);
            }
        });

        JStudentRegisterButton.setText("Cadastrar");
        JStudentRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JStudentRegisterButtonActionPerformed(evt);
            }
        });

        jRegisterStudentBirthdateLabel.setText("Data de nascimento");

        jRegisterStudentSurnameLabel.setText("Sobrenome");

        jRegisterStudentCPFLabel.setText("CPF");

        jLabel1.setText("Telefone");

        try {
            jRegisterStudentTelephoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jRegisterStudentBirthdateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jRegisterStudentBirthdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterStudentBirthdateFieldActionPerformed(evt);
            }
        });

        try {
            jRegisterStudentCPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jStudentRegisterPanelLayout = new javax.swing.GroupLayout(jStudentRegisterPanel);
        jStudentRegisterPanel.setLayout(jStudentRegisterPanelLayout);
        jStudentRegisterPanelLayout.setHorizontalGroup(
            jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStudentRegisterPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStudentRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRegisterStudentFatherNameLabel)
                            .addComponent(jRegisterStudentGenderLabel)
                            .addComponent(jRegisterStudentGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRegisterStudentFatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRegisterStudentMotherNameLabel)
                            .addComponent(jRegisterStudentMotherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStudentRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jRegisterStudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStudentRegisterPanelLayout.createSequentialGroup()
                        .addComponent(JStudentRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
            .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegisterStudentBirthdateLabel)
                            .addComponent(jRegisterStudentBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegisterStudentCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRegisterStudentCPFLabel)))
                    .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegisterStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRegisterStudentNameLabel)
                            .addComponent(jLabel1)
                            .addComponent(jRegisterStudentSurnameLabel)
                            .addComponent(jRegisterStudentSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRegisterStudentClassLabel)
                            .addComponent(jRegisterStudentTelephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jStudentRegisterPanelLayout.setVerticalGroup(
            jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegisterStudentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentSurnameLabel)
                .addGap(4, 4, 4)
                .addComponent(jRegisterStudentSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jStudentRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRegisterStudentBirthdateLabel)
                            .addComponent(jRegisterStudentCPFLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRegisterStudentBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jStudentRegisterPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jRegisterStudentCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentGenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRegisterStudentFatherNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentFatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentMotherNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentMotherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentTelephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRegisterStudentClassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegisterStudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JStudentRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        studentRegister2.add(jStudentRegisterPanel, gridBagConstraints);

        mainTabbedPane.addTab("Cadastro de Aluno", studentRegister2);

        teamRegisterPanel.setLayout(new java.awt.GridBagLayout());

        jTeamRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTeamRegisterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTeamRegisterTitle.setText("Cadastro de Time");
        jTeamRegisterTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        teamRegisterPanel.add(jTeamRegisterTitle, gridBagConstraints);

        jInnerTeamRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));
        jInnerTeamRegisterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jInnerTeamRegisterPanel.setLayout(new java.awt.GridBagLayout());

        jTeamRegisterNameLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jInnerTeamRegisterPanel.add(jTeamRegisterNameLabel, gridBagConstraints);

        jTeamRegisterNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamRegisterNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jInnerTeamRegisterPanel.add(jTeamRegisterNameField, gridBagConstraints);

        jTeamRegisterAcronymLabel.setText("Sigla");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jInnerTeamRegisterPanel.add(jTeamRegisterAcronymLabel, gridBagConstraints);

        jTeamRegisterAcronymField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamRegisterAcronymFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jInnerTeamRegisterPanel.add(jTeamRegisterAcronymField, gridBagConstraints);

        jTeamRegisterSportLabel.setText("Esporte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jInnerTeamRegisterPanel.add(jTeamRegisterSportLabel, gridBagConstraints);

        jTeamRegisterSportComboBox.setAutoscrolls(true);
        jTeamRegisterSportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamRegisterSportComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jInnerTeamRegisterPanel.add(jTeamRegisterSportComboBox, gridBagConstraints);

        jTeamRegisterClassPickerLabel.setText("Selecionar turma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jInnerTeamRegisterPanel.add(jTeamRegisterClassPickerLabel, gridBagConstraints);

        jTeamRegisterClassPickerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamRegisterClassPickerComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jInnerTeamRegisterPanel.add(jTeamRegisterClassPickerComboBox, gridBagConstraints);

        jTeamRegisterButton.setText("Cadastrar");
        jTeamRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeamRegisterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 10, 0);
        jInnerTeamRegisterPanel.add(jTeamRegisterButton, gridBagConstraints);

        jTeamRegisterStudentsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTeamRegisterStudentsScrollPane.setViewportView(jTeamRegisterStudentsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weighty = 1.0;
        jInnerTeamRegisterPanel.add(jTeamRegisterStudentsScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        teamRegisterPanel.add(jInnerTeamRegisterPanel, gridBagConstraints);

        mainTabbedPane.addTab("Cadastro de Time", teamRegisterPanel);

        coachRegister.setLayout(new java.awt.GridBagLayout());

        jCoachRegisterTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jCoachRegisterTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCoachRegisterTitle1.setText("Cadastro de Treinadores");
        jCoachRegisterTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        coachRegister.add(jCoachRegisterTitle1, gridBagConstraints);

        coachRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));
        coachRegisterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        coachSurnameLabel.setText("Sobrenome");

        coachNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachNameFieldActionPerformed(evt);
            }
        });

        coachGenderLabel.setText("Sexo");

        coachGenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachGenderFieldActionPerformed(evt);
            }
        });

        coachNameLabel1.setText("Nome");

        coachSurnameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachSurnameField1ActionPerformed(evt);
            }
        });

        coachPhoneLabel.setText("Telefone");

        coachCPFLabel.setText("CPF");

        coachBirthDateLabel.setText("Data de Nascimento");

        coachSportLabel.setText("Esporte");

        coachSportField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachSportFieldActionPerformed(evt);
            }
        });

        JCoachRegisterButton1.setText("Cadastrar");
        JCoachRegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCoachRegisterButton1ActionPerformed(evt);
            }
        });

        try {
            coachBirthDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        coachBirthDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachBirthDateFieldActionPerformed(evt);
            }
        });

        try {
            coachCPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            coachPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout coachRegisterPanelLayout = new javax.swing.GroupLayout(coachRegisterPanel);
        coachRegisterPanel.setLayout(coachRegisterPanelLayout);
        coachRegisterPanelLayout.setHorizontalGroup(
            coachRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                .addGroup(coachRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(coachRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coachSurnameLabel)
                            .addComponent(coachNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coachGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coachNameLabel1)
                            .addComponent(coachGenderLabel)
                            .addComponent(coachSurnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coachPhoneLabel)
                            .addComponent(coachCPFLabel)
                            .addComponent(coachBirthDateLabel)
                            .addComponent(coachSportLabel)
                            .addComponent(coachSportField, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(JCoachRegisterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(coachPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(coachRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(coachBirthDateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(coachCPFField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        coachRegisterPanelLayout.setVerticalGroup(
            coachRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachRegisterPanelLayout.createSequentialGroup()
                .addComponent(coachNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(coachSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachSurnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(coachGenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachPhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coachCPFLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachBirthDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachBirthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(coachSportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coachSportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JCoachRegisterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        coachRegister.add(coachRegisterPanel, gridBagConstraints);

        mainTabbedPane.addTab("Cadastro de Treinadores", coachRegister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1040, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addTournamentBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addTournamentBtnActionPerformed
        mainTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_addTournamentBtnActionPerformed

    private void searchTournamentFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_searchTournamentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTournamentFieldActionPerformed

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        registerController.updateComboBoxes();
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void JStudentRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JStudentRegisterButtonActionPerformed
        registerController.registerStudent();
    }//GEN-LAST:event_JStudentRegisterButtonActionPerformed

    private void jRegisterStudentClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentClassComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentClassComboBoxActionPerformed

    private void jRegisterStudentGenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentGenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentGenderFieldActionPerformed

    private void jRegisterStudentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentNameFieldActionPerformed

    private void jClassNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClassNameFieldActionPerformed

    private void jClassNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClassNumberActionPerformed

    private void jClassShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClassShiftActionPerformed

    private void registerClassAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerClassAction
        registerController.registerClass();
    }//GEN-LAST:event_registerClassAction

    private void jClassCycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassCycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClassCycleActionPerformed

    private void jStudentFatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudentFatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStudentFatherNameFieldActionPerformed

    private void jRegisterStudentFatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentFatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentFatherNameFieldActionPerformed

    private void jRegisterStudentMotherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentMotherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentMotherNameFieldActionPerformed

    private void jTeamRegisterNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamRegisterNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeamRegisterNameFieldActionPerformed

    private void jTeamRegisterClassPickerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamRegisterClassPickerComboBoxActionPerformed
        registerController.updateTeamTableCells(jTeamRegisterClassPickerComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_jTeamRegisterClassPickerComboBoxActionPerformed

    private void jTeamRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamRegisterButtonActionPerformed
        registerController.registerTeam(
                jTeamRegisterStudentsTable
        );
    }//GEN-LAST:event_jTeamRegisterButtonActionPerformed

    private void jTeamRegisterAcronymFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamRegisterAcronymFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeamRegisterAcronymFieldActionPerformed

    private void jTeamRegisterSportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeamRegisterSportComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeamRegisterSportComboBoxActionPerformed

    private void coachSurnameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachSurnameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachSurnameField1ActionPerformed

    private void coachGenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachGenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachGenderFieldActionPerformed

    private void coachNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachNameFieldActionPerformed

    private void coachSportFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachSportFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachSportFieldActionPerformed

    private void JCoachRegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCoachRegisterButton1ActionPerformed
        // TODO add your handling code here:
        this.registerController.createCoach();
    }//GEN-LAST:event_JCoachRegisterButton1ActionPerformed

    private void coachBirthDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachBirthDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachBirthDateFieldActionPerformed

    private void tournamentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournamentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tournamentNameFieldActionPerformed

    private void tournamentSportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournamentSportComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tournamentSportComboBoxActionPerformed

    private void tournamentRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournamentRegisterButtonActionPerformed
        // TODO add your handling code here:
        this.registerController.createTournament();
    }//GEN-LAST:event_tournamentRegisterButtonActionPerformed

    private void jRegisterStudentBirthdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterStudentBirthdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterStudentBirthdateFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JCoachRegisterButton1;
    public javax.swing.JLabel JRegisterStudentClassLabel;
    public javax.swing.JLabel JRegisterStudentFatherNameLabel;
    public javax.swing.JButton JStudentRegisterButton;
    public javax.swing.JButton addTournamentBtn;
    public javax.swing.JPanel classRegister;
    public javax.swing.JDialog classRegisterDialog;
    public javax.swing.JFormattedTextField coachBirthDateField;
    public javax.swing.JLabel coachBirthDateLabel;
    public javax.swing.JFormattedTextField coachCPFField;
    public javax.swing.JLabel coachCPFLabel;
    public javax.swing.JTextField coachGenderField;
    public javax.swing.JLabel coachGenderLabel;
    public javax.swing.JTextField coachNameField;
    public javax.swing.JLabel coachNameLabel1;
    public javax.swing.JFormattedTextField coachPhoneField;
    public javax.swing.JLabel coachPhoneLabel;
    public javax.swing.JPanel coachRegister;
    public javax.swing.JPanel coachRegisterPanel;
    public javax.swing.JTextField coachSportField;
    public javax.swing.JLabel coachSportLabel;
    public javax.swing.JTextField coachSurnameField1;
    public javax.swing.JLabel coachSurnameLabel;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton8;
    public javax.swing.JComboBox<SchoolClass.EducationalCycle> jClassCycle;
    public javax.swing.JTextField jClassNameField;
    public javax.swing.JTextField jClassNumber;
    public javax.swing.JComboBox<SchoolClass.SchoolShift> jClassShift;
    public javax.swing.JLabel jCoachRegisterTitle1;
    public javax.swing.JPanel jInnerTeamRegisterPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JFormattedTextField jRegisterStudentBirthdateField;
    public javax.swing.JLabel jRegisterStudentBirthdateLabel;
    public javax.swing.JFormattedTextField jRegisterStudentCPFField;
    public javax.swing.JLabel jRegisterStudentCPFLabel;
    public javax.swing.JComboBox<String> jRegisterStudentClassComboBox;
    public javax.swing.JTextField jRegisterStudentFatherNameField;
    public javax.swing.JTextField jRegisterStudentGenderField;
    public javax.swing.JLabel jRegisterStudentGenderLabel;
    public javax.swing.JTextField jRegisterStudentMotherNameField;
    public javax.swing.JLabel jRegisterStudentMotherNameLabel;
    public javax.swing.JTextField jRegisterStudentNameField;
    public javax.swing.JLabel jRegisterStudentNameLabel;
    public javax.swing.JTextField jRegisterStudentSurnameField;
    public javax.swing.JLabel jRegisterStudentSurnameLabel;
    public javax.swing.JFormattedTextField jRegisterStudentTelephoneField;
    public javax.swing.JPanel jStudentRegisterPanel;
    public javax.swing.JLabel jStudentRegisterTitle;
    public javax.swing.JTextField jTeamRegisterAcronymField;
    public javax.swing.JLabel jTeamRegisterAcronymLabel;
    public javax.swing.JButton jTeamRegisterButton;
    public javax.swing.JComboBox<String> jTeamRegisterClassPickerComboBox;
    public javax.swing.JLabel jTeamRegisterClassPickerLabel;
    public javax.swing.JTextField jTeamRegisterNameField;
    public javax.swing.JLabel jTeamRegisterNameLabel;
    public javax.swing.JComboBox<String> jTeamRegisterSportComboBox;
    public javax.swing.JLabel jTeamRegisterSportLabel;
    public javax.swing.JScrollPane jTeamRegisterStudentsScrollPane;
    public javax.swing.JTable jTeamRegisterStudentsTable;
    public javax.swing.JLabel jTeamRegisterTitle;
    public javax.swing.JLabel jTournamentLabel;
    public javax.swing.JScrollPane jTournamentSelectScrollPane;
    public javax.swing.JTable jTournamentSelectTable;
    public javax.swing.JPanel mainBottomPanel;
    public javax.swing.JPanel mainInnerBottomPanel;
    public javax.swing.JPanel mainInnerTopPanel;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JSeparator mainSeparator;
    public javax.swing.JTabbedPane mainTabbedPane;
    public javax.swing.JPanel mainTopPanel;
    public javax.swing.JButton searchTournamentBtn;
    public javax.swing.JTextField searchTournamentField;
    public javax.swing.JPanel studentRegister2;
    public javax.swing.JDialog studentRegisterDialog;
    public javax.swing.JPanel teamRegisterPanel;
    public javax.swing.JLabel title;
    public javax.swing.JLabel title4;
    public javax.swing.JFormattedTextField tournamentEndDateField;
    public javax.swing.JLabel tournamentEndDateLabel;
    public javax.swing.JTextField tournamentNameField;
    public javax.swing.JLabel tournamentNameLabel;
    public javax.swing.JPanel tournamentRegister;
    public javax.swing.JButton tournamentRegisterButton;
    public javax.swing.JPanel tournamentRegisterPanel;
    public java.awt.ScrollPane tournamentScrollPane;
    public javax.swing.JComboBox<String> tournamentSportComboBox;
    public javax.swing.JLabel tournamentSportLabel;
    public javax.swing.JFormattedTextField tournamentStartDateField;
    public javax.swing.JLabel tournamentStartDateLabel;
    public javax.swing.JLabel tournamentTeamsLabel;
    // End of variables declaration//GEN-END:variables
}
